[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "d-des"
version = "0.1.0"
authors = [
  { name="Dua Amir", email="duaamir392004@gmail.com" },
]
description = "Dynamic Data Encryption Standard (D-DES) with a single dynamic S-box."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security :: Cryptography",
]

[project.urls]
"Homepage" = "https://github.com/duaamir39/d-des.git"

[project.scripts]
ddes-cli = "ddes.cli:main"
